name: CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Lighthouse CI Action
      uses: treosh/lighthouse-ci-action@v1
      with:
        urls: 'http://milesalex.github.io/gatsby'

    - name: Upload results
      uses: actions/upload-artifact@master
      with:
        name: lighthouse-results
        path: './results'
